openapi: 3.0.0
info:
  title: API Documentation
  description: API documentation for my Node.js app
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /user:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IdUsers:
                      type: integer
                    Login:
                      type: string
                    Password:
                      type: string
